-- Move players to Tier 2 (Set 1)
-- This updates the set_no to 1 (Tier 2) and sets updated_at to ensure they appear at the end of the list.
-- EXISTING STATS ARE PRESERVED.

UPDATE players 
SET set_no = 1, 
    updated_at = NOW() 
WHERE name IN (
    'Aiden Markram',
    'Jofra Archer',
    'Romario Shephard',
    'Tim Southee',
    'Shubman Gill',
    'Tim David',
    'Ishan Kishan',
    'Josh Hazlewood',
    'Hashim Amla',
    'Marcus Stoinis',
    'Joe Root',
    'Kagiso Rabada',
    'Tim Seifert',
    'Ravindra Jadeja',
    'Pathum Nissanka',
    'Nicholas Pooran',
    'Harshit Rana',
    'Steve Smith',
    'Lungi Ngidi',
    'Heinrich Klaasen',
    'Yashasvi Jaiswal',
    'Ben Stokes',
    'Trent Boult',
    'Rinku Singh',
    'Josh Inglis',
    'Bhuvneshwar Kumar',
    'Ross Taylor',
    'Sunil Narine',
    'Ravichandran Ashwin',
    'Reeza Hendricks',
    'Noor Ahmad',
    'MS Dhoni',
    'Lasith Malinga',
    'Ruturaj Gaikwad',
    'Keshav Maharaj',
    'Ashish Wadekar',
    'Dwayne Bravo',
    'Deepak Chahar',
    'Ryan Rickleton',
    'Shikhar Dhawan',
    'Glenn Maxwell',
    'Faf Du Plessis',
    'Ravi Bishnoi',
    'Jitesh Sharma',
    'Kane Williamson',
    'Cameron Green',
    'Rovman Powell',
    'Imran Tahir',
    'Jacob Bethell',
    'Shivam Dube'
);
